tardiness_reports	CREATE TABLE `tardiness_reports` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `tard_rep_num` varchar(30) NOT NULL,
  `report_date` date NOT NULL,
  `monitoring_officer_id` bigint(20) unsigned NOT NULL,
  `student_id` bigint(20) unsigned NOT NULL,
  `student_name` varchar(150) NOT NULL,
  `department_id` bigint(20) unsigned NOT NULL,
  `department_name` varchar(100) NOT NULL,
  `grade_level` varchar(50) NOT NULL,
  `section` varchar(100) NOT NULL,
  `reason_id` bigint(20) unsigned NOT NULL,
  `reason_name` varchar(150) NOT NULL,
  `supplementary_observations` text DEFAULT NULL,
  `actions_taken` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_tardiness_reports_number` (`tard_rep_num`),
  KEY `idx_tardiness_reports_student` (`student_id`),
  KEY `idx_tardiness_reports_department` (`department_id`),
  KEY `idx_tardiness_reports_reason` (`reason_id`),
  KEY `idx_tardiness_reports_officer` (`monitoring_officer_id`),
  KEY `idx_tardiness_reports_date` (`report_date`),
  CONSTRAINT `fk_tardiness_reports_department` FOREIGN KEY (`department_id`) REFERENCES `student_level_departments` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `fk_tardiness_reports_reason` FOREIGN KEY (`reason_id`) REFERENCES `reasons` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `fk_tardiness_reports_student` FOREIGN KEY (`student_id`) REFERENCES `students` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci	
